#-------------------------------------------------
#
# Project created by QtCreator 2015-06-05T16:14:52
#
#-------------------------------------------------

QT       += core \
            gui \
            qml \
            serialport

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = qDroneShow
TEMPLATE = app

INCLUDEPATH += include/ \
    libs/

SOURCES += \
    src/main.cpp \
    src/mainwindow.cpp \
    libs/Vehicle/UAS.cc \
    libs/Vehicle/MAVLinkProtocol.cc \
    libs/Vehicle/QGCTemporaryFile.cc \
    libs/Vehicle/LinkManager.cc \
    libs/Vehicle/LinkConfiguration.cc \
    libs/Vehicle/SerialLink.cc \
    libs/Vehicle/TCPLink.cc \
    libs/Vehicle/UDPLink.cc \
    libs/Vehicle/QGCSingleton.cc \
    libs/Vehicle/QGC.cc \
    libs/QGC/LinkConfiguration.cc \
    libs/QGC/LinkManager.cc \
    libs/QGC/MAVLinkProtocol.cc \
    libs/QGC/QGC.cc \
    libs/QGC/QGCSingleton.cc \
    libs/QGC/QGCTemporaryFile.cc \
    libs/QGC/SerialLink.cc \
    libs/QGC/TCPLink.cc \
    libs/QGC/UAS.cc \
    libs/QGC/UDPLink.cc \
    libs/UAV/uav.cpp \
    libs/UAV/mavlinkmessage.cpp \
    libs/UAV/link.cpp \
    libs/UAV/mavlinkheartbeat.cpp \
    libs/UAV/mavlinkcommand.cpp \
    libs/UAV/bytebuffer.cpp

HEADERS  += include/mainwindow.h \
    libs/Vehicle/UASInterface.h \
    libs/Vehicle/UAS.h \
    libs/Vehicle/MAVLinkProtocol.h \
    libs/Vehicle/QGCMAVLink.h \
    libs/Vehicle/LinkInterface.h \
    libs/MAVLink/ardupilotmega/ardupilotmega.h \
    libs/MAVLink/ardupilotmega/mavlink.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_ahrs.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_ahrs2.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_ahrs3.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_airspeed_autocal.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_ap_adc.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_autopilot_version_request.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_battery2.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_camera_feedback.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_camera_status.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_compassmot_status.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_data16.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_data32.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_data64.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_data96.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_digicam_configure.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_digicam_control.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_fence_fetch_point.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_fence_point.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_fence_status.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_gimbal_control.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_gimbal_report.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_hwstatus.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_limits_status.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_meminfo.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_mount_configure.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_mount_control.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_mount_status.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_radio.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_rally_fetch_point.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_rally_point.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_rangefinder.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_sensor_offsets.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_set_mag_offsets.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_simstate.h \
    libs/MAVLink/ardupilotmega/mavlink_msg_wind.h \
    libs/MAVLink/ardupilotmega/testsuite.h \
    libs/MAVLink/ardupilotmega/version.h \
    libs/MAVLink/ASLUAV/ASLUAV.h \
    libs/MAVLink/ASLUAV/mavlink.h \
    libs/MAVLink/ASLUAV/mavlink_msg_asl_obctrl.h \
    libs/MAVLink/ASLUAV/mavlink_msg_aslctrl_data.h \
    libs/MAVLink/ASLUAV/mavlink_msg_aslctrl_debug.h \
    libs/MAVLink/ASLUAV/mavlink_msg_asluav_status.h \
    libs/MAVLink/ASLUAV/mavlink_msg_ekf_ext.h \
    libs/MAVLink/ASLUAV/mavlink_msg_sens_atmos.h \
    libs/MAVLink/ASLUAV/mavlink_msg_sens_mppt.h \
    libs/MAVLink/ASLUAV/mavlink_msg_sens_power.h \
    libs/MAVLink/ASLUAV/testsuite.h \
    libs/MAVLink/ASLUAV/version.h \
    libs/MAVLink/autoquad/autoquad.h \
    libs/MAVLink/autoquad/mavlink.h \
    libs/MAVLink/autoquad/mavlink_msg_aq_telemetry_f.h \
    libs/MAVLink/autoquad/testsuite.h \
    libs/MAVLink/autoquad/version.h \
    libs/MAVLink/common/common.h \
    libs/MAVLink/common/mavlink.h \
    libs/MAVLink/common/mavlink_msg_actuator_control_target.h \
    libs/MAVLink/common/mavlink_msg_att_pos_mocap.h \
    libs/MAVLink/common/mavlink_msg_attitude.h \
    libs/MAVLink/common/mavlink_msg_attitude_quaternion.h \
    libs/MAVLink/common/mavlink_msg_attitude_quaternion_cov.h \
    libs/MAVLink/common/mavlink_msg_attitude_target.h \
    libs/MAVLink/common/mavlink_msg_auth_key.h \
    libs/MAVLink/common/mavlink_msg_autopilot_version.h \
    libs/MAVLink/common/mavlink_msg_battery_status.h \
    libs/MAVLink/common/mavlink_msg_change_operator_control.h \
    libs/MAVLink/common/mavlink_msg_change_operator_control_ack.h \
    libs/MAVLink/common/mavlink_msg_command_ack.h \
    libs/MAVLink/common/mavlink_msg_command_int.h \
    libs/MAVLink/common/mavlink_msg_command_long.h \
    libs/MAVLink/common/mavlink_msg_data_stream.h \
    libs/MAVLink/common/mavlink_msg_data_transmission_handshake.h \
    libs/MAVLink/common/mavlink_msg_debug.h \
    libs/MAVLink/common/mavlink_msg_debug_vect.h \
    libs/MAVLink/common/mavlink_msg_distance_sensor.h \
    libs/MAVLink/common/mavlink_msg_encapsulated_data.h \
    libs/MAVLink/common/mavlink_msg_file_transfer_protocol.h \
    libs/MAVLink/common/mavlink_msg_global_position_int.h \
    libs/MAVLink/common/mavlink_msg_global_position_int_cov.h \
    libs/MAVLink/common/mavlink_msg_global_vision_position_estimate.h \
    libs/MAVLink/common/mavlink_msg_gps2_raw.h \
    libs/MAVLink/common/mavlink_msg_gps2_rtk.h \
    libs/MAVLink/common/mavlink_msg_gps_global_origin.h \
    libs/MAVLink/common/mavlink_msg_gps_inject_data.h \
    libs/MAVLink/common/mavlink_msg_gps_raw_int.h \
    libs/MAVLink/common/mavlink_msg_gps_rtk.h \
    libs/MAVLink/common/mavlink_msg_gps_status.h \
    libs/MAVLink/common/mavlink_msg_heartbeat.h \
    libs/MAVLink/common/mavlink_msg_highres_imu.h \
    libs/MAVLink/common/mavlink_msg_hil_controls.h \
    libs/MAVLink/common/mavlink_msg_hil_gps.h \
    libs/MAVLink/common/mavlink_msg_hil_optical_flow.h \
    libs/MAVLink/common/mavlink_msg_hil_rc_inputs_raw.h \
    libs/MAVLink/common/mavlink_msg_hil_sensor.h \
    libs/MAVLink/common/mavlink_msg_hil_state.h \
    libs/MAVLink/common/mavlink_msg_hil_state_quaternion.h \
    libs/MAVLink/common/mavlink_msg_local_position_ned.h \
    libs/MAVLink/common/mavlink_msg_local_position_ned_cov.h \
    libs/MAVLink/common/mavlink_msg_local_position_ned_system_global_offset.h \
    libs/MAVLink/common/mavlink_msg_log_data.h \
    libs/MAVLink/common/mavlink_msg_log_entry.h \
    libs/MAVLink/common/mavlink_msg_log_erase.h \
    libs/MAVLink/common/mavlink_msg_log_request_data.h \
    libs/MAVLink/common/mavlink_msg_log_request_end.h \
    libs/MAVLink/common/mavlink_msg_log_request_list.h \
    libs/MAVLink/common/mavlink_msg_manual_control.h \
    libs/MAVLink/common/mavlink_msg_manual_setpoint.h \
    libs/MAVLink/common/mavlink_msg_memory_vect.h \
    libs/MAVLink/common/mavlink_msg_mission_ack.h \
    libs/MAVLink/common/mavlink_msg_mission_clear_all.h \
    libs/MAVLink/common/mavlink_msg_mission_count.h \
    libs/MAVLink/common/mavlink_msg_mission_current.h \
    libs/MAVLink/common/mavlink_msg_mission_item.h \
    libs/MAVLink/common/mavlink_msg_mission_item_int.h \
    libs/MAVLink/common/mavlink_msg_mission_item_reached.h \
    libs/MAVLink/common/mavlink_msg_mission_request.h \
    libs/MAVLink/common/mavlink_msg_mission_request_list.h \
    libs/MAVLink/common/mavlink_msg_mission_request_partial_list.h \
    libs/MAVLink/common/mavlink_msg_mission_set_current.h \
    libs/MAVLink/common/mavlink_msg_mission_write_partial_list.h \
    libs/MAVLink/common/mavlink_msg_named_value_float.h \
    libs/MAVLink/common/mavlink_msg_named_value_int.h \
    libs/MAVLink/common/mavlink_msg_nav_controller_output.h \
    libs/MAVLink/common/mavlink_msg_optical_flow.h \
    libs/MAVLink/common/mavlink_msg_optical_flow_rad.h \
    libs/MAVLink/common/mavlink_msg_param_map_rc.h \
    libs/MAVLink/common/mavlink_msg_param_request_list.h \
    libs/MAVLink/common/mavlink_msg_param_request_read.h \
    libs/MAVLink/common/mavlink_msg_param_set.h \
    libs/MAVLink/common/mavlink_msg_param_value.h \
    libs/MAVLink/common/mavlink_msg_ping.h \
    libs/MAVLink/common/mavlink_msg_position_target_global_int.h \
    libs/MAVLink/common/mavlink_msg_position_target_local_ned.h \
    libs/MAVLink/common/mavlink_msg_power_status.h \
    libs/MAVLink/common/mavlink_msg_radio_status.h \
    libs/MAVLink/common/mavlink_msg_raw_imu.h \
    libs/MAVLink/common/mavlink_msg_raw_pressure.h \
    libs/MAVLink/common/mavlink_msg_rc_channels.h \
    libs/MAVLink/common/mavlink_msg_rc_channels_override.h \
    libs/MAVLink/common/mavlink_msg_rc_channels_raw.h \
    libs/MAVLink/common/mavlink_msg_rc_channels_scaled.h \
    libs/MAVLink/common/mavlink_msg_request_data_stream.h \
    libs/MAVLink/common/mavlink_msg_safety_allowed_area.h \
    libs/MAVLink/common/mavlink_msg_safety_set_allowed_area.h \
    libs/MAVLink/common/mavlink_msg_scaled_imu.h \
    libs/MAVLink/common/mavlink_msg_scaled_imu2.h \
    libs/MAVLink/common/mavlink_msg_scaled_pressure.h \
    libs/MAVLink/common/mavlink_msg_scaled_pressure2.h \
    libs/MAVLink/common/mavlink_msg_serial_control.h \
    libs/MAVLink/common/mavlink_msg_servo_output_raw.h \
    libs/MAVLink/common/mavlink_msg_set_actuator_control_target.h \
    libs/MAVLink/common/mavlink_msg_set_attitude_target.h \
    libs/MAVLink/common/mavlink_msg_set_gps_global_origin.h \
    libs/MAVLink/common/mavlink_msg_set_mode.h \
    libs/MAVLink/common/mavlink_msg_set_position_target_global_int.h \
    libs/MAVLink/common/mavlink_msg_set_position_target_local_ned.h \
    libs/MAVLink/common/mavlink_msg_sim_state.h \
    libs/MAVLink/common/mavlink_msg_statustext.h \
    libs/MAVLink/common/mavlink_msg_sys_status.h \
    libs/MAVLink/common/mavlink_msg_system_time.h \
    libs/MAVLink/common/mavlink_msg_terrain_check.h \
    libs/MAVLink/common/mavlink_msg_terrain_data.h \
    libs/MAVLink/common/mavlink_msg_terrain_report.h \
    libs/MAVLink/common/mavlink_msg_terrain_request.h \
    libs/MAVLink/common/mavlink_msg_timesync.h \
    libs/MAVLink/common/mavlink_msg_v2_extension.h \
    libs/MAVLink/common/mavlink_msg_vfr_hud.h \
    libs/MAVLink/common/mavlink_msg_vicon_position_estimate.h \
    libs/MAVLink/common/mavlink_msg_vision_position_estimate.h \
    libs/MAVLink/common/mavlink_msg_vision_speed_estimate.h \
    libs/MAVLink/common/testsuite.h \
    libs/MAVLink/common/version.h \
    libs/MAVLink/matrixpilot/matrixpilot.h \
    libs/MAVLink/matrixpilot/mavlink.h \
    libs/MAVLink/matrixpilot/mavlink_msg_airspeeds.h \
    libs/MAVLink/matrixpilot/mavlink_msg_altitudes.h \
    libs/MAVLink/matrixpilot/mavlink_msg_flexifunction_buffer_function.h \
    libs/MAVLink/matrixpilot/mavlink_msg_flexifunction_buffer_function_ack.h \
    libs/MAVLink/matrixpilot/mavlink_msg_flexifunction_command.h \
    libs/MAVLink/matrixpilot/mavlink_msg_flexifunction_command_ack.h \
    libs/MAVLink/matrixpilot/mavlink_msg_flexifunction_directory.h \
    libs/MAVLink/matrixpilot/mavlink_msg_flexifunction_directory_ack.h \
    libs/MAVLink/matrixpilot/mavlink_msg_flexifunction_read_req.h \
    libs/MAVLink/matrixpilot/mavlink_msg_flexifunction_set.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f13.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f14.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f15.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f16.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f2_a.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f2_b.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f4.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f5.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f6.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f7.h \
    libs/MAVLink/matrixpilot/mavlink_msg_serial_udb_extra_f8.h \
    libs/MAVLink/matrixpilot/testsuite.h \
    libs/MAVLink/matrixpilot/version.h \
    libs/MAVLink/minimal/mavlink.h \
    libs/MAVLink/minimal/mavlink_msg_heartbeat.h \
    libs/MAVLink/minimal/minimal.h \
    libs/MAVLink/minimal/testsuite.h \
    libs/MAVLink/minimal/version.h \
    libs/MAVLink/pixhawk/mavlink.h \
    libs/MAVLink/pixhawk/mavlink_msg_attitude_control.h \
    libs/MAVLink/pixhawk/mavlink_msg_brief_feature.h \
    libs/MAVLink/pixhawk/mavlink_msg_detection_stats.h \
    libs/MAVLink/pixhawk/mavlink_msg_image_available.h \
    libs/MAVLink/pixhawk/mavlink_msg_image_trigger_control.h \
    libs/MAVLink/pixhawk/mavlink_msg_image_triggered.h \
    libs/MAVLink/pixhawk/mavlink_msg_marker.h \
    libs/MAVLink/pixhawk/mavlink_msg_onboard_health.h \
    libs/MAVLink/pixhawk/mavlink_msg_pattern_detected.h \
    libs/MAVLink/pixhawk/mavlink_msg_point_of_interest.h \
    libs/MAVLink/pixhawk/mavlink_msg_point_of_interest_connection.h \
    libs/MAVLink/pixhawk/mavlink_msg_position_control_setpoint.h \
    libs/MAVLink/pixhawk/mavlink_msg_raw_aux.h \
    libs/MAVLink/pixhawk/mavlink_msg_set_cam_shutter.h \
    libs/MAVLink/pixhawk/mavlink_msg_set_position_control_offset.h \
    libs/MAVLink/pixhawk/mavlink_msg_watchdog_command.h \
    libs/MAVLink/pixhawk/mavlink_msg_watchdog_heartbeat.h \
    libs/MAVLink/pixhawk/mavlink_msg_watchdog_process_info.h \
    libs/MAVLink/pixhawk/mavlink_msg_watchdog_process_status.h \
    libs/MAVLink/pixhawk/pixhawk.h \
    libs/MAVLink/pixhawk/testsuite.h \
    libs/MAVLink/pixhawk/version.h \
    libs/MAVLink/slugs/mavlink.h \
    libs/MAVLink/slugs/mavlink_msg_boot.h \
    libs/MAVLink/slugs/mavlink_msg_control_surface.h \
    libs/MAVLink/slugs/mavlink_msg_cpu_load.h \
    libs/MAVLink/slugs/mavlink_msg_ctrl_srfc_pt.h \
    libs/MAVLink/slugs/mavlink_msg_data_log.h \
    libs/MAVLink/slugs/mavlink_msg_diagnostic.h \
    libs/MAVLink/slugs/mavlink_msg_gps_date_time.h \
    libs/MAVLink/slugs/mavlink_msg_isr_location.h \
    libs/MAVLink/slugs/mavlink_msg_mid_lvl_cmds.h \
    libs/MAVLink/slugs/mavlink_msg_novatel_diag.h \
    libs/MAVLink/slugs/mavlink_msg_ptz_status.h \
    libs/MAVLink/slugs/mavlink_msg_sensor_bias.h \
    libs/MAVLink/slugs/mavlink_msg_sensor_diag.h \
    libs/MAVLink/slugs/mavlink_msg_slugs_camera_order.h \
    libs/MAVLink/slugs/mavlink_msg_slugs_configuration_camera.h \
    libs/MAVLink/slugs/mavlink_msg_slugs_mobile_location.h \
    libs/MAVLink/slugs/mavlink_msg_slugs_navigation.h \
    libs/MAVLink/slugs/mavlink_msg_status_gps.h \
    libs/MAVLink/slugs/mavlink_msg_uav_status.h \
    libs/MAVLink/slugs/mavlink_msg_volt_sensor.h \
    libs/MAVLink/slugs/slugs.h \
    libs/MAVLink/slugs/testsuite.h \
    libs/MAVLink/slugs/version.h \
    libs/MAVLink/test/mavlink.h \
    libs/MAVLink/test/mavlink_msg_test_types.h \
    libs/MAVLink/test/test.h \
    libs/MAVLink/test/testsuite.h \
    libs/MAVLink/test/version.h \
    libs/MAVLink/ualberta/mavlink.h \
    libs/MAVLink/ualberta/mavlink_msg_nav_filter_bias.h \
    libs/MAVLink/ualberta/mavlink_msg_radio_calibration.h \
    libs/MAVLink/ualberta/mavlink_msg_ualberta_sys_status.h \
    libs/MAVLink/ualberta/testsuite.h \
    libs/MAVLink/ualberta/ualberta.h \
    libs/MAVLink/ualberta/version.h \
    libs/MAVLink/checksum.h \
    libs/MAVLink/mavlink_conversions.h \
    libs/MAVLink/mavlink_helpers.h \
    libs/MAVLink/mavlink_types.h \
    libs/MAVLink/protocol.h \
    libs/Vehicle/QGCTemporaryFile.h \
    libs/Vehicle/LinkManager.h \
    libs/Vehicle/LinkConfiguration.h \
    libs/Vehicle/SerialInterface.h \
    libs/Vehicle/SerialLink.h \
    libs/Vehicle/TCPLink.h \
    libs/Vehicle/UDPLink.h \
    libs/Vehicle/QGCSingleton.h \
    libs/Vehicle/ProtocolInterface.h \
    libs/Vehicle/QGCConfig.h \
    libs/Vehicle/QGC.h \
    libs/QGC/LinkConfiguration.h \
    libs/QGC/LinkInterface.h \
    libs/QGC/LinkManager.h \
    libs/QGC/MAVLinkProtocol.h \
    libs/QGC/ProtocolInterface.h \
    libs/QGC/QGC.h \
    libs/QGC/QGCConfig.h \
    libs/QGC/QGCMAVLink.h \
    libs/QGC/QGCSingleton.h \
    libs/QGC/QGCTemporaryFile.h \
    libs/QGC/SerialInterface.h \
    libs/QGC/SerialLink.h \
    libs/QGC/TCPLink.h \
    libs/QGC/UAS.h \
    libs/QGC/UASInterface.h \
    libs/QGC/UDPLink.h \
    libs/UAV/uav.h \
    libs/UAV/mavlinkmessage.h \
    libs/UAV/link.h \
    libs/UAV/mavlinkheartbeat.h \
    libs/UAV/mavlinkcommand.h \
    libs/UAV/bytebuffer.h \
    libs/UAV/mavlinkcmd.h

FORMS    += mainwindow.ui
